version: "3"

services:
  db:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    network_mode: bridge
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example # user is root
    volumes:
      - "$PWD/mysql:/var/lib/mysql"
      - "/var/run/docker.sock:/var/run/docker.sock"

  adminer:
    image: "adminer:latest"
    network_mode: bridge
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 4447:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
